Replace HSQLDB 1.8 with H2 Database 2.4.240
HSQLDB 1.8.0.10 (released 2005) is unmaintained. Replace with
H2 Database 2.4.240, which is actively maintained, faster, and
provides better SQL compatibility.

Changes:
- Maven dependency: hsqldb:hsqldb:1.8.0.10 → com.h2database:h2:2.4.240
- JDBC driver: org.hsqldb.jdbcDriver → org.h2.Driver
- JDBC URLs: jdbc:hsqldb:file: → jdbc:h2:file:, jdbc:hsqldb:hsql:// → jdbc:h2:tcp://
- SQL: NOW() → CURRENT_TIMESTAMP, convert() → CAST(), TEXT TABLE → CSVREAD()
- Test URLs: DB_CLOSE_DELAY=-1 for connection stability
- DaoConfig: null-safe property handling
- Tests: explicit commit after DDL, separated DROP/CREATE statements
- Samples: renamed sample/hsqldb/ → sample/h2/, sample/ldap2hsqldb/ → sample/ldap2h2/
- Shell scripts: rewritten for H2 CLI tools (Shell, Server, Console)
- Packaging: Debian/RPM/assembly updated for h2
- LICENSE.txt: replaced HSQLDB license with H2 MPL 2.0 + EPL 1.0

diff --git a/bin/h2 b/bin/h2
--- a/bin/h2
+++ b/bin/h2
@@ -6,10 +6,10 @@
 # identities from a list of data sources including any database with a JDBC
 # connector, another LDAP directory, flat files...
 #
-# LSC automatically embed HSQLDB library. So, this script could :
-# - Launch a HSQLDB server ;
+# LSC automatically embeds H2 database library. So, this script could :
+# - Launch an H2 TCP server ;
 # - Inject CSV data into it ;
-# - Shutdown the HSQLDB server previously started.
+# - Shutdown the H2 server previously started.
 #
 # ---------------------------------------------------------------------------------
 #
@@ -21,10 +21,10 @@
 #
 #   * Redistributions of source code must retain the above copyright notice, this
 #     list of conditions and the following disclaimer.
-#   * Redistributions in binary form must reproduce the above copyright notice,
+#   * Redistributions in binary form must reproduce the above copyright notice,
 #     this list of conditions and the following disclaimer in the documentation
 #     and/or other materials provided with the distribution.
-#   * Neither the name of the LSC Project nor the names of its contributors may be
+#   * Neither the name of the LSC Project nor the names of its contributors may be
 #     used to endorse or promote products derived from this software without
 #     specific prior written permission.
 #
@@ -61,20 +61,20 @@ fi
 CFG_DIR="$LSC_HOME/etc"
 LIB_DIR="$LSC_HOME/lib"
 LOG_DIR="/tmp"
-LOG_FILE="$LOG_DIR/hsqldb.log"
+LOG_FILE="$LOG_DIR/h2.log"
 VAR_DIR="$LSC_HOME/var"
 
-# HSQLDB jar file
-HSQLDB_LIB=$LIB_DIR/hsqldb*.jar
+# H2 jar file
+H2_LIB=$LIB_DIR/h2*.jar
 
-# Temporary directory so that HSQLDB server could store files
-HSQLDB_DIR=$VAR_DIR/hsqldb
+# Temporary directory so that H2 server could store files
+H2_DIR=$VAR_DIR/h2
 
-# HSQLDB server PID file
-HSQLDB_PIDFILE=$VAR_DIR/hsqldb.pid
+# H2 server PID file
+H2_PIDFILE=$VAR_DIR/h2.pid
 
 # Table name
-HSQLDB_TABLE=csvdata
+H2_TABLE=csvdata
 
 # Default CSV separator
 CSV_SEPARATOR=";"
@@ -83,29 +83,29 @@ CSV_SEPARATOR=";"
 # FUNCTIONS
 # ---------------------------------------------------------------------------------
 function log() {
-  echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [hsqldb] $1" >> "$LOG_FILE"
+  echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [h2] $1" >> "$LOG_FILE"
 }
 
 function fatal() {
   log $1
-  echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [hsqldb] $1" 1>&2
+  echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [h2] $1" 1>&2
 }
 
 #
-# Drop all data from the HSQLDB instance.
+# Drop all data from the H2 instance.
 #
 data_drop()
 {
-  hsqldb_sqlQuery "DROP TABLE $HSQLDB_TABLE;" 2> /dev/null
+  h2_sqlQuery "DROP TABLE IF EXISTS $H2_TABLE" 2> /dev/null
   if [ $? -eq 0 ]; then
-    log "Table $HSQLDB_TABLE deleted"
+    log "Table $H2_TABLE deleted"
   else
-    fatal "Unable to delete table $HSQLDB_TABLE"
+    fatal "Unable to delete table $H2_TABLE"
   fi
 }
 
 #
-# Create the SQL table into the HSQLDB database. All field are read from the first
+# Create the SQL table into the H2 database. All field are read from the first
 # line of the CSV file passed in the first parameter. Once the table is created,
 # data should be correctly imported.
 #
@@ -113,63 +113,35 @@ data_import()
 {
   # $1 : CSV fullpath
   # $2 : CSV separator
-  HSQLDB_TABLEDEF=""
-  IFSO=$IFS
-  IFS=$2
-  for field in `head -n 1 $1`; do
-    if [ -n "$HSQLDB_TABLEDEF" ]; then
-      HSQLDB_TABLEDEF="$HSQLDB_TABLEDEF, $field VARCHAR"
-    else
-      HSQLDB_TABLEDEF="$field VARCHAR"
-    fi
-  done
-  IFS=$IOFS
-  if [ -n "$HSQLDB_TABLEDEF" ]; then
-    hsqldb_sqlQuery "CREATE TEXT TABLE $HSQLDB_TABLE ($HSQLDB_TABLEDEF);"
-    if [ $? -eq 0 ]; then
-      log "Table $HSQLDB_TABLE created"
-      nblines=`cat $1 | wc -l`
-      scale=`echo $nblines | awk '{ print int(log($0/3)/log(2))+1 }'`
-      cp $1 $HSQLDB_DIR/`basename $1`
-      sep=`hsqldb_checkCsvSeparator $2`
-      encoding=`file $1  2> /dev/null | cut -d' ' -f2`
-      source="`basename $1`;ignore_first=true;cache_scale=$scale;fs=$sep"
-      if [ "x$encoding" == "xUTF-8" ] ; then
-	source=$source";encoding=UTF-8"
-      fi
-      hsqldb_sqlQuery "SET TABLE $HSQLDB_TABLE SOURCE \"$source\";" > /dev/null 2>&1
-      if [ $? -eq 0 ]; then
-        log "File $1 imported into $HSQLDB_TABLE ($nblines rows)"
-	echo "$nblines lines imported into table $HSQLDB_TABLE"
-      else
-        fatal "Unable to import $1 into table $HSQLDB_TABLE"
-      fi
-      rm -f $HSQLDB_DIR/`basename $1` > /dev/null 2>&1
-      return
-    fi
+  h2_sqlQuery "CREATE TABLE $H2_TABLE AS SELECT * FROM CSVREAD('$1')"
+  if [ $? -eq 0 ]; then
+    nblines=$(tail -n +2 "$1" | wc -l)
+    log "File $1 imported into $H2_TABLE ($nblines rows)"
+    echo "$nblines lines imported into table $H2_TABLE"
+  else
+    fatal "Unable to import $1 into table $H2_TABLE"
   fi
-  exit 1
 }
 
 #
-# Show data from the HSQLDB instance.
+# Show data from the H2 instance.
 #
 data_show()
 {
-  hsqldb_sqlQuery "SELECT * FROM $HSQLDB_TABLE;" 2> /dev/null
+  h2_sqlQuery "SELECT * FROM $H2_TABLE" 2> /dev/null
 }
 
 #
-# Check if the HSQLDB server is running or not. This function should check a
+# Check if the H2 server is running or not. This function should check a
 # process from the PIDFILE into the process list.
 #
-hsqldb_checkInstance()
+h2_checkInstance()
 {
-  if [ ! -e $HSQLDB_PIDFILE ]; then
+  if [ ! -e $H2_PIDFILE ]; then
     echo 1
     return
   fi
-  pid=`cat $HSQLDB_PIDFILE`
+  pid=`cat $H2_PIDFILE`
   if [ `ps -e | grep $pid | grep -v "grep $pid" | wc -l` -eq 0 ]; then
     echo 1
     return
@@ -178,85 +150,55 @@ hsqldb_checkInstance()
 }
 
 #
-# Return the CSV separator used by hsqldb.
-#
-hsqldb_checkCsvSeparator()
-{
-  # $1 : A separator
-  case "$1" in
-    ";")
-      echo -n "\semi"
-      ;;
-    "\"")
-      echo -n "\quote"
-      ;;
-    " ")
-      echo -n "\space"
-      ;;
-    "'")
-      echo -n "\apos"
-      ;;
-    *)
-      echo -n $1
-      ;;
-  esac
-}
-
-#
-# Remove all data on disk that have been created by an hsqldb server. No checks
+# Remove all data on disk that have been created by an h2 server. No checks
 # on a running process are performed, so be carefull.
 #
-hsqldb_cleanData()
+h2_cleanData()
 {
-  cd $HSQLDB_DIR > /dev/null 2>&1
+  cd $H2_DIR > /dev/null 2>&1
   if [ $? -eq 0 ]; then
     rm -f *
     cd ..
-    rmdir `basename $HSQLDB_DIR`
+    rmdir `basename $H2_DIR`
   fi
-  rm -f $HSQLDB_PIDFILE > /dev/null 2>&1
+  rm -f $H2_PIDFILE > /dev/null 2>&1
 }
 
 #
-# Perform a SQL query on the running HSQLDB instance. No checks on a running
+# Perform a SQL query on the H2 database. No checks on a running
 # process are performed, so be carefull.
 #
-hsqldb_sqlQuery()
+h2_sqlQuery()
 {
   # $1 : sql query
-  java -jar $HSQLDB_LIB --rcFile $HSQLDB_DIR/hsqldb.rc --sql "$1" lscdb
+  java -cp $H2_LIB org.h2.tools.Shell -url "jdbc:h2:file:${H2_DIR}/lscdb" -user sa -password "" -sql "$1"
 }
 
 #
-# Start an instance of a HSQLDB server. No checks on a running process are
-# performed, so be carefull. It will also build a RC file for futur auto
-# authentication.
+# Start an instance of a H2 TCP server. No checks on a running process are
+# performed, so be carefull.
 #
-hsqldb_startServer()
+h2_startServer()
 {
-  mkdir -p $HSQLDB_DIR
-  java -cp $HSQLDB_LIB org.hsqldb.Server \
-    -database.0 file:$HSQLDB_DIR/mydb -dbname.0 lscdb -address 127.0.0.1 > /dev/null 2>&1 &
-  echo $! > $HSQLDB_PIDFILE
+  mkdir -p $H2_DIR
+  java -cp $H2_LIB org.h2.tools.Server \
+    -tcpAllowOthers -ifNotExists -tcpPassword "" > /dev/null 2>&1 &
+  echo $! > $H2_PIDFILE
   sleep 2
-  if [ ! -d $HSQLDB_DIR ]; then
-    mkdir $HSQLDB_DIR
+  if [ ! -d $H2_DIR ]; then
+    mkdir $H2_DIR
   fi
-  echo "
-    urlid lscdb
-    url jdbc:hsqldb:hsql://localhost/lscdb
-    username sa
-    password" > $HSQLDB_DIR/hsqldb.rc
 }
 
 #
-# Hard stop the current instance of HSQLDB server. It means that it will send a
+# Hard stop the current instance of H2 server. It means that it will send a
 # SIGKILL on the process found through the PIDFILE. No checks on a running process
 # are performed, so be carefull.
 #
-hsqldb_stopServer()
+h2_stopServer()
 {
-  kill -s KILL `cat $HSQLDB_PIDFILE`
+  java -cp $H2_LIB org.h2.tools.Server -tcpShutdown tcp://localhost:9092 -tcpPassword "" 2> /dev/null
+  kill -s KILL `cat $H2_PIDFILE` 2> /dev/null
 }
 
 # ---------------------------------------------------------------------------------
@@ -271,7 +213,7 @@ case "$1" in
   "--drop")
     shift
     if [ "$1" != "" ]; then
-      HSQLDB_TABLE="$1"
+      H2_TABLE="$1"
       shift
     fi
     ACTIONS="$ACTIONS dropdata"
@@ -282,7 +224,7 @@ case "$1" in
     CSV_FILE="$1"
     shift
     if [ "$1" != "" ]; then
-      HSQLDB_TABLE="$1"
+      H2_TABLE="$1"
       shift
     fi
     if [ "$1" != "" ]; then
@@ -294,7 +236,7 @@ case "$1" in
   "--show")
     shift
     if [ "$1" != "" ]; then
-      HSQLDB_TABLE="$1"
+      H2_TABLE="$1"
       shift
     fi
     ACTIONS="$ACTIONS showdata"
@@ -334,7 +276,7 @@ esac
 for action in $ACTIONS; do
   case "$action" in
     "dropdata")
-      if [ `hsqldb_checkInstance` -eq 1 ]; then
+      if [ `h2_checkInstance` -eq 1 ]; then
         echo " Error - server is not running"
         exit 1
       fi
@@ -345,43 +287,42 @@ for action in $ACTIONS; do
         echo " Error - file '$CSV_FILE' not found"
         exit 1
       fi
-      if [ `hsqldb_checkInstance` -eq 1 ]; then
+      if [ `h2_checkInstance` -eq 1 ]; then
         echo " Error - server is not running"
         exit 1
       fi
       data_import "$CSV_FILE" "$CSV_SEPARATOR"
       ;;
     "showdata")
-      if [ `hsqldb_checkInstance` -eq 1 ]; then
+      if [ `h2_checkInstance` -eq 1 ]; then
         echo " Error - server is not running"
         exit 1
       fi
       data_show
       ;;
     "startserver")
-      if [ `hsqldb_checkInstance` -eq 0 ]; then
+      if [ `h2_checkInstance` -eq 0 ]; then
         echo " Error - server already running"
         exit 1
       fi
-      hsqldb_cleanData
-      hsqldb_startServer
+      h2_cleanData
+      h2_startServer
       ;;
     "stopserver")
-      if [ `hsqldb_checkInstance` -eq 0 ]; then
-        hsqldb_stopServer
-        hsqldb_cleanData
+      if [ `h2_checkInstance` -eq 0 ]; then
+        h2_stopServer
+        h2_cleanData
       fi
       ;;
     "status")
-      if [ `hsqldb_checkInstance` -eq 0 ]; then
-        pid=`cat $HSQLDB_PIDFILE`
-	echo "HSQLDB Server is running (PID $pid)"
+      if [ `h2_checkInstance` -eq 0 ]; then
+        pid=`cat $H2_PIDFILE`
+	echo "H2 Server is running (PID $pid)"
         exit 0
       else
-	echo "HSQLDB Server is not running"
+	echo "H2 Server is not running"
         exit 1
       fi
 
   esac
 done
-
diff --git a/sample/h2/bin/lsc-sample b/sample/h2/bin/lsc-sample
--- a/sample/h2/bin/lsc-sample
+++ b/sample/h2/bin/lsc-sample
@@ -6,10 +6,10 @@
 # identities from a list of data sources including any database with a JDBC
 # connector, another LDAP directory, flat files...
 #
-# LSC automatically embeds HSQLDB library. So, this script can:
-# - Create a table from a CSV file header in a HSQLDB database;
-# - Inject CSV data into a HSQLDB database;
-# - Read data from a HSQLDB database table.
+# LSC automatically embeds H2 database library. So, this script can:
+# - Create a table from a CSV file header in an H2 database;
+# - Inject CSV data into an H2 database;
+# - Read data from an H2 database table.
 #
 # ---------------------------------------------------------------------------------
 #
@@ -21,10 +21,10 @@
 #
 #   * Redistributions of source code must retain the above copyright notice, this
 #     list of conditions and the following disclaimer.
-#   * Redistributions in binary form must reproduce the above copyright notice,
+#   * Redistributions in binary form must reproduce the above copyright notice,
 #     this list of conditions and the following disclaimer in the documentation
 #     and/or other materials provided with the distribution.
-#   * Neither the name of the LSC Project nor the names of its contributors may be
+#   * Neither the name of the LSC Project nor the names of its contributors may be
 #     used to endorse or promote products derived from this software without
 #     specific prior written permission.
 #
@@ -62,15 +62,13 @@ CONFIGPATH="${SAMPLE_HOME}/etc"
 LSC_LIB_DIR="${SAMPLE_HOME}/../../lib"
 LSC_BIN_DIR="${SAMPLE_HOME}/../../bin"
 
-# HSQLDB jar file
-[ -z "$HSQLDB_LIB" -a -e "${LSC_LIB_DIR}"/hsqldb*.jar ] && HSQLDB_LIB=$( readlink -f "${LSC_LIB_DIR}"/hsqldb*.jar )
-[ -z "$HSQLDB_LIB" ] && echo "hsqldb driver (hsqldb*.jar) is missing" && exit 1
-# Temporary directory so that HSQLDB server could store files
-HSQLDB_DIR="/tmp/lsc/hsqldb"
-# HSQLDB configuration file
-HSQLDB_RC="${SAMPLE_HOME}/etc/hsqldb.rc"
+# H2 jar file
+[ -z "$H2_LIB" -a -e "${LSC_LIB_DIR}"/h2*.jar ] && H2_LIB=$( readlink -f "${LSC_LIB_DIR}"/h2*.jar )
+[ -z "$H2_LIB" ] && echo "h2 driver (h2*.jar) is missing" && exit 1
+# Temporary directory so that H2 server could store files
+H2_DIR="/tmp/lsc/h2"
 # Table name
-HSQLDB_TABLE="csvdata"
+H2_TABLE="csvdata"
 # Default CSV separator
 CSV_SEPARATOR=";"
 
@@ -79,15 +77,15 @@ CSV_SEPARATOR=";"
 # ---------------------------------------------------------------------------------
 
 #
-# Drop all data from the HSQLDB instance.
+# Drop all data from the H2 instance.
 #
 data_drop()
 {
-  hsqldb_sqlQuery "DROP TABLE $HSQLDB_TABLE; SHUTDOWN;"
+  h2_sqlQuery "DROP TABLE IF EXISTS $H2_TABLE"
 }
 
 #
-# Create the SQL table into the HSQLDB database. All field are read from the first
+# Create the SQL table into the H2 database. All field are read from the first
 # line of the CSV file passed in the first parameter. Once the table is created,
 # data should be correctly imported.
 #
@@ -95,103 +93,52 @@ data_import()
 {
   # $1 : CSV fullpath
   # $2 : CSV separator
-  HSQLDB_TABLEDEF=""
-  IFSO=$IFS
-  IFS=$2
-  for field in `head -n 1 $1`; do
-    if [ -n "$HSQLDB_TABLEDEF" ]; then
-      HSQLDB_TABLEDEF="$HSQLDB_TABLEDEF, $field VARCHAR"
-    else
-      HSQLDB_TABLEDEF="$field VARCHAR"
-    fi
-  done
-  IFS=$IOFS
-	mkdir -p $HSQLDB_DIR
-  if [ -n "$HSQLDB_TABLEDEF" ]; then
-    hsqldb_sqlQuery "CREATE TEXT TABLE $HSQLDB_TABLE ($HSQLDB_TABLEDEF); SHUTDOWN;"
-    if [ $? -eq 0 ]; then
-	  echo "Table $HSQLDB_TABLE created"
-      nblines=`cat $1 | wc -l`
-      let nblines--
-			
-      tail -n $nblines $1 > $HSQLDB_DIR/`basename $1`
-      sep=`hsqldb_checkCsvSeparator $2`
-		encoding=`file $1  2> /dev/null | cut -d' ' -f2`
-		if [ "x$encoding" == "xUTF-8" ] ; then
-			hsqldb_sqlQuery "SET TABLE $HSQLDB_TABLE SOURCE \"`basename $1`;fs=$sep;encoding=UTF-8\"; SHUTDOWN;" > /dev/null 2>&1
-		else
-			hsqldb_sqlQuery "SET TABLE $HSQLDB_TABLE SOURCE \"`basename $1`;fs=$sep\"; SHUTDOWN;" > /dev/null 2>&1
-		fi
-	  if [ $? -eq 0 ]; then
-		  echo "$nblines lines added to table $HSQLDB_TABLE"
-		  return
-	  fi
-    fi
+  mkdir -p $H2_DIR
+  h2_sqlQuery "CREATE TABLE $H2_TABLE AS SELECT * FROM CSVREAD('$1')"
+  if [ $? -eq 0 ]; then
+    nblines=$(tail -n +2 "$1" | wc -l)
+    echo "$nblines lines imported into table $H2_TABLE"
+    return
   fi
   exit 1
 }
 
 #
-# Show data from the HSQLDB instance.
+# Show data from the H2 instance.
 #
 data_show()
 {
-  hsqldb_sqlQuery "SELECT * FROM $HSQLDB_TABLE;"
+  h2_sqlQuery "SELECT * FROM $H2_TABLE"
 }
 
 #
-# Return the CSV separator used by hsqldb.
-#
-hsqldb_checkCsvSeparator()
-{
-  # $1 : A separator
-  case "$1" in
-    ";")
-      echo -n "\semi"
-      ;;
-    "\"")
-      echo -n "\quote"
-      ;;
-    " ")
-      echo -n "\space"
-      ;;
-    "'")
-      echo -n "\apos"
-      ;;
-    *)
-      echo -n $1
-      ;;
-  esac
-}
-
-#
-# Remove all data on disk that have been created by an hsqldb server. No checks
+# Remove all data on disk that have been created by an h2 server. No checks
 # on a running process are performed, so be carefull.
 #
-hsqldb_cleanData()
+h2_cleanData()
 {
   oldpwd=`pwd`
-  cd ${HSQLDB_DIR} > /dev/null 2>&1
+  cd ${H2_DIR} > /dev/null 2>&1
   if [ $? -eq 0 ]; then
     rm -f *
     cd ..
-    rmdir `basename "${HSQLDB_DIR}"`
+    rmdir `basename "${H2_DIR}"`
   fi
   cd ${oldpwd}
 }
 
 #
-# Perform a SQL query on the running HSQLDB instance. No checks on a running
+# Perform a SQL query on the H2 database. No checks on a running
 # process are performed, so be carefull.
 #
-hsqldb_sqlQuery()
+h2_sqlQuery()
 {
   # $1 : sql query
 
 	# check if we have java executable
 	get_java
 
-	"${JAVA_COMMAND}" -jar "$HSQLDB_LIB" --rcFile "$HSQLDB_RC" --sql "$1" lscdb
+	"${JAVA_COMMAND}" -cp "$H2_LIB" org.h2.tools.Shell -url "jdbc:h2:file:${H2_DIR}/lscdb" -user sa -password "" -sql "$1"
 }
 
 # Determine where the java exectuable is
@@ -207,8 +154,8 @@ function get_java() {
     if [ -e "$JAVA_COMMAND" ]; then return; fi
 
     # Nothing seems approprite, warn and exit
-    log "No java executable found on PATH or in JAVA_HOME! Aborting."
-    log "Define JAVA_HOME or adjust your PATH variable to include java."
+    echo "No java executable found on PATH or in JAVA_HOME! Aborting."
+    echo "Define JAVA_HOME or adjust your PATH variable to include java."
     exit 2
 }
 
@@ -284,7 +231,7 @@ case "$1" in
     echo " One option from available options is:"
     echo "   --import <file> [<separator>]    Import data from CSV file"
     echo "   --show    Show data from database"
-    echo "   --drop    Drop the table $HSQLDB_TABLE from database"
+    echo "   --drop    Drop the table $H2_TABLE from database"
     echo "   --start-ldap-server    Launch an embedded OpenDJ LDAP server"
     echo "   --run     Run the synchronization task"
 	echo "   --clean   Remove all files from disk"
@@ -315,11 +262,10 @@ for action in $ACTIONS; do
       start_ldap
       ;;
     "cleandata")
-      hsqldb_cleanData
+      h2_cleanData
       ;;
     "cleanldapdata")
       rm -rf /tmp/opendj-test
       ;;
   esac
 done
-
diff --git a/sample/ldap2h2/bin/lsc-sample b/sample/ldap2h2/bin/lsc-sample
--- a/sample/ldap2h2/bin/lsc-sample
+++ b/sample/ldap2h2/bin/lsc-sample
@@ -6,10 +6,10 @@
 # identities from a list of data sources including any database with a JDBC
 # connector, another LDAP directory, flat files...
 #
-# LSC automatically embeds HSQLDB library. So, this script can:
-# - Create a table from a CSV file header in a HSQLDB database;
-# - Inject CSV data into a HSQLDB database;
-# - Read data from a HSQLDB database table.
+# LSC automatically embeds H2 database library. So, this script can:
+# - Create a table from a CSV file header in an H2 database;
+# - Inject CSV data into an H2 database;
+# - Read data from an H2 database table.
 #
 # ---------------------------------------------------------------------------------
 #
@@ -21,10 +21,10 @@
 #
 #   * Redistributions of source code must retain the above copyright notice, this
 #     list of conditions and the following disclaimer.
-#   * Redistributions in binary form must reproduce the above copyright notice,
+#   * Redistributions in binary form must reproduce the above copyright notice,
 #     this list of conditions and the following disclaimer in the documentation
 #     and/or other materials provided with the distribution.
-#   * Neither the name of the LSC Project nor the names of its contributors may be
+#   * Neither the name of the LSC Project nor the names of its contributors may be
 #     used to endorse or promote products derived from this software without
 #     specific prior written permission.
 #
@@ -62,18 +62,14 @@ CONFIGPATH="${SAMPLE_HOME}/etc"
 LSC_LIB_DIR="${SAMPLE_HOME}/../../lib"
 LSC_BIN_DIR="${SAMPLE_HOME}/../../bin"
 
-# HSQLDB jar file
-[ -z "$HSQLDB_LIB" -a -e "${LSC_LIB_DIR}"/hsqldb*.jar ] && HSQLDB_LIB=$( readlink -f "${LSC_LIB_DIR}"/hsqldb*.jar )
-[ -z "$HSQLDB_LIB" ] && echo "hsqldb driver (hsqldb*.jar) is missing" && exit 1
-# Temporary directory so that HSQLDB server could store files
-HSQLDB_DIR=/tmp/lsc/hsqldb
-# HSQLDB configuration file
-HSQLDB_RC=$SAMPLE_HOME/etc/hsqldb.rc
-# HSQLDB server properties file
-HSQLDB_PROP=$SAMPLE_HOME/etc/server.properties
+# H2 jar file
+[ -z "$H2_LIB" -a -e "${LSC_LIB_DIR}"/h2*.jar ] && H2_LIB=$( readlink -f "${LSC_LIB_DIR}"/h2*.jar )
+[ -z "$H2_LIB" ] && echo "h2 driver (h2*.jar) is missing" && exit 1
+# Temporary directory so that H2 server could store files
+H2_DIR=/tmp/lsc/h2
 # Table name
-HSQLDB_TABLE=userdata
-HSQLDB_TABLEDEF="ID VARCHAR,UID VARCHAR,MAIL VARCHAR,MAIL_LOWER VARCHAR,LAST_UPDATE TIMESTAMP, STATUS BOOLEAN, ENDOFVALIDITY VARCHAR,SN VARCHAR,CN VARCHAR,GIVENNAME VARCHAR,O VARCHAR,ADDRESS VARCHAR,TELEPHONENUMBER VARCHAR,CARLICENSE VARCHAR"
+H2_TABLE=userdata
+H2_TABLEDEF="ID VARCHAR,UID VARCHAR,MAIL VARCHAR,MAIL_LOWER VARCHAR,LAST_UPDATE TIMESTAMP, STATUS BOOLEAN, ENDOFVALIDITY VARCHAR,SN VARCHAR,CN VARCHAR,GIVENNAME VARCHAR,O VARCHAR,ADDRESS VARCHAR,TELEPHONENUMBER VARCHAR,CARLICENSE VARCHAR"
 # Default CSV separator
 CSV_SEPARATOR=";"
 
@@ -82,62 +78,61 @@ CSV_SEPARATOR=";"
 # ---------------------------------------------------------------------------------
 
 #
-# Drop all data from the HSQLDB instance.
+# Drop all data from the H2 instance.
 #
 data_drop()
 {
-  hsqldb_sqlQuery "DROP TABLE ${HSQLDB_TABLE};"
+  h2_sqlQuery "DROP TABLE IF EXISTS ${H2_TABLE}"
 }
 
 #
-# Create table in the HSQLDB instance.
+# Create table in the H2 instance.
 #
 data_create()
 {
-	hsqldb_sqlQuery "CREATE TABLE ${HSQLDB_TABLE} (${HSQLDB_TABLEDEF});"
+	h2_sqlQuery "CREATE TABLE ${H2_TABLE} (${H2_TABLEDEF})"
 }
 
 #
-# Show data from the HSQLDB instance.
+# Show data from the H2 instance.
 #
 data_show()
 {
-  hsqldb_sqlQuery "SELECT * FROM ${HSQLDB_TABLE};"
+  h2_sqlQuery "SELECT * FROM ${H2_TABLE}"
 }
 
 #
-# Remove all data on disk that have been created by an hsqldb server. No checks
+# Remove all data on disk that have been created by an h2 server. No checks
 # on a running process are performed, so be carefull.
 #
-hsqldb_cleanData()
+h2_cleanData()
 {
   oldpwd=`pwd`
-  cd ${HSQLDB_DIR} > /dev/null 2>&1
+  cd ${H2_DIR} > /dev/null 2>&1
   if [ $? -eq 0 ]; then
     rm -f *
     cd ..
-    rmdir `basename "${HSQLDB_DIR}"`
+    rmdir `basename "${H2_DIR}"`
   fi
   cd ${oldpwd}
 }
 
 #
-# Perform a SQL query on the running HSQLDB instance. No checks on a running
+# Perform a SQL query on the H2 database. No checks on a running
 # process are performed, so be carefull.
 #
-hsqldb_sqlQuery()
+h2_sqlQuery()
 {
   # $1 : sql query
-        #echo "Run hsqldb_sqlQuery: $1"
 	# check if we have java executable
 	get_java
 
-	"${JAVA_COMMAND}" -jar "$HSQLDB_LIB" --rcFile "$HSQLDB_RC" --sql "$1" lscdb
+	"${JAVA_COMMAND}" -cp "$H2_LIB" org.h2.tools.Shell -url "jdbc:h2:file:${H2_DIR}/lscdb" -user sa -password "" -sql "$1"
 	erg=$?
 	if [ $erg -eq 0 ]; then
 		echo "Command executed successfully"
 	fi
-	exit $erg
+	return $erg
 }
 
 # Determine where the java exectuable is
@@ -153,8 +148,8 @@ function get_java() {
     if [ -e "$JAVA_COMMAND" ]; then return; fi
 
     # Nothing seems approprite, warn and exit
-    log "No java executable found on PATH or in JAVA_HOME! Aborting."
-    log "Define JAVA_HOME or adjust your PATH variable to include java."
+    echo "No java executable found on PATH or in JAVA_HOME! Aborting."
+    echo "Define JAVA_HOME or adjust your PATH variable to include java."
     exit 2
 }
 
@@ -178,19 +173,33 @@ start_ldap() {
 	run_java_command "org.lsc.opendj.LdapServer -a -f ${CONFIGPATH}"
 }
 
-start_hsql() {
-	echo "Starting HSQL server on localhost ..."
-	run_java_command "org.hsqldb.Server" -database.0 "file:/tmp/hsqldb/ldap2sql" -dbname.0 lscdb 
+start_h2() {
+	echo "Starting H2 TCP server on localhost:9092 ..."
+	mkdir -p ${H2_DIR}
+	get_java
+	"${JAVA_COMMAND}" -cp "$H2_LIB" org.h2.tools.Server -tcpAllowOthers -ifNotExists -tcpPassword "" &
+	echo $! > ${H2_DIR}/h2.pid
+	sleep 2
+	echo "H2 TCP server started"
 }
 
-stop_hsql() {
-	run_java_command "org.hsqldb.util.ShutdownServer" -url "jdbc:hsqldb:hsql://localhost/lscdb" 
+stop_h2() {
+	if [ -f ${H2_DIR}/h2.pid ]; then
+		get_java
+		"${JAVA_COMMAND}" -cp "$H2_LIB" org.h2.tools.Server -tcpShutdown tcp://localhost:9092 -tcpPassword ""
+		rm -f ${H2_DIR}/h2.pid
+		echo "H2 TCP server stopped"
+	else
+		echo "H2 TCP server is not running"
+	fi
 }
 
 start_dbtool() {
-	echo "Starting HSQL Database Manager ..."
-	run_java_command "org.hsqldb.util.DatabaseManager" -url "jdbc:hsqldb:hsql://localhost/lscdb"
+	echo "Starting H2 Console ..."
+	get_java
+	"${JAVA_COMMAND}" -cp "$H2_LIB" org.h2.tools.Console
 }
+
 run() {
 	SYNCTASK=$1
 	if [ -z "$SYNCTASK" ]; then
@@ -241,13 +250,13 @@ case "$1" in
     ACTIONS="$ACTIONS startldap"
 	shift
 	;;
-  "--start-hsql-server")
-    ACTIONS="$ACTIONS starthsql"
+  "--start-h2-server")
+    ACTIONS="$ACTIONS starth2"
 	shift
 	;;
-  "--stop-hsql-server")
-    ACTIONS="$ACTIONS stophsql"
-!	shift
+  "--stop-h2-server")
+    ACTIONS="$ACTIONS stoph2"
+	shift
 	;;
   "--run")
 	run LDAP2JDBCTask LDAP2JDBCTask
@@ -267,13 +276,13 @@ case "$1" in
     echo ""
     echo " One option from available options is:"
     echo "  Database:"
-    echo "   --start-hsql-server    Launch an embedded HSQL DB server"
-    echo "   --stop-hsql-server     Halt an embedded HSQL DB server"
-    echo "   --create               Create the table $HSQLDB_TABLE in database"
+    echo "   --start-h2-server      Launch an embedded H2 TCP server"
+    echo "   --stop-h2-server       Halt an embedded H2 TCP server"
+    echo "   --create               Create the table $H2_TABLE in database"
     echo "   --show                 Show data from database"
-    echo "   --dbtool               Start DB Tool"
+    echo "   --dbtool               Start H2 Console"
     echo "   --sql <command>        run sql command"
-    echo "   --drop                 Drop the table $HSQLDB_TABLE from database"
+    echo "   --drop                 Drop the table $H2_TABLE from database"
     echo "  LDAP"
     echo "   --start-ldap-server    Launch an embedded OpenDJ LDAP server"
     echo "  Other functions"
@@ -300,7 +309,7 @@ for action in $ACTIONS; do
       data_show
       ;;
     "sql")
-      hsqldb_sqlQuery "$SQL_COMMAND"
+      h2_sqlQuery "$SQL_COMMAND"
       ;;
     "startldap")
       start_ldap
@@ -308,21 +317,20 @@ for action in $ACTIONS; do
     "stopldap")
       stop_ldap
       ;;
-    "starthsql")
-      start_hsql
+    "starth2")
+      start_h2
       ;;
-    "stophsql")
-      stop_hsql
+    "stoph2")
+      stop_h2
       ;;
     "startdbtool")
       start_dbtool
       ;;
     "cleandata")
-      hsqldb_cleanData
+      h2_cleanData
       ;;
     "cleanldapdata")
       rm -rf /tmp/opendj-test
       ;;
   esac
 done
-
